name: build-ios-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Slack:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # Firebase
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Bundle Install
      run: bundle install

    # Xcode 11.2.1
    # - name: Select Xcode version
    #   run: sudo xcode-select -s '/Applications/Xcode_11.2.1.app'

    # - name: Show Xcode version
    #   run: xcodebuild -version

    # Slack Notify
    - name: Slack
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
      run: |
        bundle exec fastlane test_notify

# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   Test:
#     # The type of runner that the job will run on
# #    runs-on: ubuntu-latest
#     runs-on: macos-latest
#     timeout-minutes: 45

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#       - uses: actions/setup-ruby@v1
#         with:
#           ruby-version: '3.0.2'
#       - uses: maierj/fastlane-action@v2.0.1
#         with:
#           # lane: 'firebase'
#          lane: 'test_notify'
